// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrzKHhqnavZKI0AbEe5Le3s35ORybtN7c',
    appId: '1:890333090304:web:8891067f7be59c51cb7ee5',
    messagingSenderId: '890333090304',
    projectId: 'aureacanvas',
    authDomain: 'aureacanvas.firebaseapp.com',
    storageBucket: 'aureacanvas.firebasestorage.app',
    measurementId: 'G-ZT7XCRJR5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkFnTOpBda0fgcV0TsMdjPUKSXfa99iN8',
    appId: '1:890333090304:android:42bb4d8e23cbce0bcb7ee5',
    messagingSenderId: '890333090304',
    projectId: 'aureacanvas',
    storageBucket: 'aureacanvas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChQR82A8XDY7nVwoA5uvPjG08KDolyE7k',
    appId: '1:890333090304:ios:856e14ff4d784b08cb7ee5',
    messagingSenderId: '890333090304',
    projectId: 'aureacanvas',
    storageBucket: 'aureacanvas.firebasestorage.app',
    iosBundleId: 'com.logiflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChQR82A8XDY7nVwoA5uvPjG08KDolyE7k',
    appId: '1:890333090304:ios:856e14ff4d784b08cb7ee5',
    messagingSenderId: '890333090304',
    projectId: 'aureacanvas',
    storageBucket: 'aureacanvas.firebasestorage.app',
    iosBundleId: 'com.logiflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrzKHhqnavZKI0AbEe5Le3s35ORybtN7c',
    appId: '1:890333090304:web:fa676f16366b28cacb7ee5',
    messagingSenderId: '890333090304',
    projectId: 'aureacanvas',
    authDomain: 'aureacanvas.firebaseapp.com',
    storageBucket: 'aureacanvas.firebasestorage.app',
    measurementId: 'G-047ND4GWJD',
  );
}
